spring.application.name=resume-ai-optimizer

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=openai/gpt-oss-120b
spring.ai.openai.chat.options.temperature=0.4

server.port=8080

springdoc.swagger-ui.path=/swagger-ui.html